### ISSUE TITLE
Arrow keys dont work when you hit the 'start game' button playing locally

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/liberty-bikes#228] opened 2019-09-26 17:10 UTC
Noticed that arrow control keys don't work when playing local, and you hit the 'start game' button (vs waiting for the count down clock to wait 20 seconds).  If you wait the 20 seconds, the arrow keys work fine.

**Comment by olendvcook** [comment] 2019-09-26 17:11
They also start working if you click anywhere on the game map or up by the party code after clicking start game, I think it's something with the window losing focus after clicking the start game button.

**Comment by hlhoots** [comment] 2019-09-26 17:13
Cool - will give that a try.  Thanks Olen!

**Comment by realModusOperandi** [comment] 2019-09-27 20:43
Hey, what OS/browser(s) are you seeing this in? I wasn't able to reproduce this myself but I might not be trying the right combination.

**Comment by aguibert** [comment] 2019-10-08 22:15
I'm pretty sure the issue here is not having browser focus, so the keystrokes aren't registering with the window at all.

Going to close this issue unless we get an indication otherwise

**Comment by olendvcook** [comment] 2019-10-08 22:23
it's true that it's from not having browser focus, the issue is that hitting the start button loses browser focus which is weird.

This is happened to me on Firefox Quantum 69.0.1 (32-bit) but not chrome

**Comment by realModusOperandi** [comment] 2019-10-08 22:37
I can't reproduce it on that browser. Does your browser window actually go into the inactive state?

**Comment by realModusOperandi** [comment] 2019-10-08 22:40
OK, it's Windows only. And no amount of clicking anywhere lets me actually control the bike. Something is weird, wouldn't be surprised if this is a FF/Windows bug.

**Comment by olendvcook** [comment] 2019-10-08 22:41
:sadstevebalmer: you can click up by where the party code should be and then it works

**Closed** 2019-10-09 16:31 UTC
Labels: bug
